Drupal chart: Fix failing postupgrade drush commands
wunderio/drupal-project-k8s pull request #313
Opened 2021-03-24 13:03 UTC by Rade333

Changes proposed in this PR:
- reorder the default postupgrade commands in Drupal chart so that cache rebuild is the very first command being run
- apparently my IDE removed a bunch of whitespaces as well

Link to Slack discussion: https://wunder.slack.com/archives/C8UN6AG9W/p1616578842088100

2021-03-24 13:53 UTC, Jancis requested changes
drush `cache-rebuild` fails when the bootstrap can't be executed
> Command cache-rebuild needs a higher bootstrap level to run - you    [error]
> will need to invoke drush from a more functional Drupal environment
> to run this command.

This means a repeated deployment will fail and You won't be able to have successful deployment until You import the database (which might not be possible if shell was not enabled on the first run (postinstall vs postupgrade).

Based on this, the change can't be accepted, unfortunately.

I would be very happy to accept the whitespace fixes, though :)

2021-04-08 06:48 UTC, Rade333 commented
> drush `cache-rebuild` fails when the bootstrap can't be executed
> 
> > Command cache-rebuild needs a higher bootstrap level to run - you    [error]
> > will need to invoke drush from a more functional Drupal environment
> > to run this command.
> 
> This means a repeated deployment will fail and You won't be able to have successful deployment until You import the database (which might not be possible if shell was not enabled on the first run (postinstall vs postupgrade).
> 
> Based on this, the change can't be accepted, unfortunately.
> 
> I would be very happy to accept the whitespace fixes, though :)

Thanks for the feedback!

I did notice that drush cr does _not_ fail when run on an empty database. To my understanding, when the deploy process reaches the postupgrade commands, the database already exists (even though it may be empty), and the credentials should be in order for drush to be able to connect to it, right? So in that case this shouldn't be a problem, but maybe I'm missing something here?

2021-04-19 07:18 UTC, Jancis commented
You're correct, I was testing without database. Drush status returns with exit code 0 when the database is there, but empty, so this should be fine after all. Thank You for re-checking it!

2021-04-19 07:18 UTC, Jancis approved these changes

2021-04-19 08:34 UTC, merged